use log::{error, trace};
use thiserror::Error;

use bitcoin::{
    blockdata::{
        locktime::absolute::LockTime,
        transaction::{self, Transaction, TxOut},
    },
    consensus::Encodable,
};

use bitcoincore_rpc::{
    json::{EstimateMode, FundRawTransactionOptions, ListUnspentResultEntry},
    Client, RawTx, RpcApi,
};

pub fn fund_tx(
    rpc: &Client,
    tx: Transaction,
    mode: Option<EstimateMode>,
) -> Result<Transaction, WalletError> {
    trace!("Funding transaction: {:?}", &tx);

    // Regular rust-bitcoin serialization is not working because bitcoincore_rpc
    // uses legacy serialization for transaction with no inputs, whereas rust-bitcoin library
    // still uses segwit serialization. Raw hex generated by rust-bitcoin has the marker and flag
    // which is not accepted by the bitcoin core RPC.
    //
    // let tx_hex = tx.raw_hex();
    // let tx_hex = bitcoin::consensus::serialize(&tx);
    // let tx_hex = bitcoin::consensus::encode::serialize_hex(&tx);
    //
    // See this issue for more info: https://github.com/rust-bitcoin/rust-bitcoin/issues/2238
    //
    // This is copied from the rust-bitcoin library, but with the serialization done manually
    // in the legacy way, without the segwit marker and flag.
    //
    // The marker and flag are included back after the signing via sign_raw_transaction_with_wallet.
    let tx_hex = {
        let mut tx_hex = Vec::new();
        tx.version
            .consensus_encode(&mut tx_hex)
            .map_err(|_| WalletError::FundTxSerializeError(tx.clone()))?;
        tx.input
            .consensus_encode(&mut tx_hex)
            .map_err(|_| WalletError::FundTxSerializeError(tx.clone()))?;
        tx.output
            .consensus_encode(&mut tx_hex)
            .map_err(|_| WalletError::FundTxSerializeError(tx.clone()))?;
        tx.lock_time
            .consensus_encode(&mut tx_hex)
            .map_err(|_| WalletError::FundTxSerializeError(tx.clone()))?;
        tx_hex
    };

    trace!("Funding transaction RPC param: {}", hex::encode(&tx_hex));

    let estimate_mode = mode.or(Some(EstimateMode::Economical));

    let opts = FundRawTransactionOptions {
        // place change tx last
        change_position: Some(tx.output.len() as u32),
        estimate_mode,
        ..Default::default()
    };

    let funded = rpc.fund_raw_transaction(&tx_hex, Some(&opts), None)?;
    let funded_tx: Transaction = funded.transaction()?;

    trace!("Funded transaction: {}", funded_tx.raw_hex());

    Ok(funded_tx)
}

pub fn fund_outputs(
    rpc: &Client,
    outputs: Vec<TxOut>,
    mode: Option<EstimateMode>,
) -> Result<Transaction, WalletError> {
    let tx = Transaction {
        version: transaction::Version::TWO,
        lock_time: LockTime::ZERO,
        input: Vec::with_capacity(0),
        output: outputs,
    };

    let funded_tx: Transaction = fund_tx(rpc, tx, mode)?;

    Ok(funded_tx)
}

pub fn sign_tx(rpc: &Client, unsigned_tx: Transaction) -> Result<Transaction, WalletError> {
    let signed_raw_transaction = rpc.sign_raw_transaction_with_wallet(&unsigned_tx, None, None)?;
    if !signed_raw_transaction.complete {
        return Err(WalletError::IncompleteSignature(hex::encode(
            signed_raw_transaction.hex,
        )));
    }
    Ok(signed_raw_transaction.transaction()?)
}

pub fn get_new_address(rpc: &Client) -> Result<bitcoin::Address, WalletError> {
    Ok(rpc.get_new_address(None, None)?.assume_checked())
}

pub fn get_unspent_for_address(
    rpc: &Client,
    addr: &bitcoin::Address,
) -> Result<Vec<ListUnspentResultEntry>, WalletError> {
    let unspent = rpc.list_unspent(None, None, Some(&[addr]), None, None)?;
    Ok(unspent)
}

/// Imports an address descriptor into the wallet
pub fn import_address(
    rpc: &Client,
    addr: &bitcoin::Address,
    label: String,
) -> Result<(), bitcoincore_rpc::Error> {
    let raw_descriptor = format!("addr({})", addr);
    let descriptor_info = rpc.get_descriptor_info(&raw_descriptor)?;
    let descriptor = descriptor_info.descriptor;

    let req = bitcoincore_rpc::json::ImportDescriptors {
        descriptor,
        label: Some(label),
        timestamp: bitcoincore_rpc::json::Timestamp::Now,
        active: None,
        range: None,
        next_index: None,
        internal: None,
    };
    rpc.import_descriptors(req)?;
    Ok(())
}

#[derive(Error, Debug)]
pub enum WalletError {
    #[error(transparent)]
    BitcoinRpcError(#[from] bitcoincore_rpc::Error),

    #[error(transparent)]
    BitcoinEncodeError(#[from] bitcoin::consensus::encode::Error),

    #[error("could not serialize transaction for funding: {0:?}")]
    FundTxSerializeError(Transaction),

    #[error("transaction signed but not complete {0}")]
    IncompleteSignature(String),
}
